@startuml Academic

actor Mahasiswa as mhs
actor Dosen as dsn
actor Admin as adm

package Classroom {
    usecase "Pilih mata kuliah" as U1
    usecase "Jadwal kuliah" as U2
    usecase "Ruang perkuliahan" as U3
    usecase "Menerima penjadwalan perkuliahan" as U4
    usecase "Mengajar" as U7
    usecase "Mengirim nilai" as U5
    usecase "Tolak mengajar" as U6
    usecase "Mengatur ruang perkuliahan" as U8
    usecase "Mengatur jadwal kuliah" as U9
}

mhs --> U1
U1 .> U2 : include
U1 .> U3 : include
mhs --> U4 
dsn --> U7 
U7 .> U6 : extend
U7 .> U5 : extend
adm --> U8
adm --> U9
U9 .> U2 : include
U8 .> U3 : include

@enduml